sanitize_slug() {
  local value="${1,,}"
  value="${value//_/-}"
  value="$(printf '%s' "$value" | sed -E 's/[^a-z0-9.-]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
  [[ -n "$value" ]] || die "Unable to derive a valid project slug."
  [[ "$value" != .* && "$value" != *..* ]] || die "Unsafe project slug: $value"
  printf '%s' "$value"
}

slug_from_repo_url() {
  local url="$1" name
  name="${url%/}"; name="${name##*/}"; name="${name%.git}"
  sanitize_slug "$name"
}

repo_owner_name() {
  local url="$1" path owner repo
  path="${url#https://github.com/}"; path="${path#http://github.com/}"; path="${path#git@github.com:}"
  path="${path%.git}"; path="${path%/}"
  owner="${path%%/*}"; repo="${path#*/}"
  [[ "$owner" =~ ^[A-Za-z0-9_.-]+$ && "$repo" =~ ^[A-Za-z0-9_.-]+$ && "$owner" != "$repo" ]] || return 1
  printf '%s/%s' "$owner" "$repo"
}

canonical_repo_url() {
  local full="$1"
  printf 'https://github.com/%s' "$full"
}

arch_name() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'x64' ;;
    aarch64|arm64) printf 'arm64' ;;
    armv7l|armv6l) printf 'arm' ;;
    *) die "Unsupported architecture: $(uname -m)" ;;
  esac
}

node_arch_name() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'x64' ;;
    aarch64|arm64) printf 'arm64' ;;
    armv7l|armv6l) printf 'armv7l' ;;
    *) die "Unsupported Node.js architecture: $(uname -m)" ;;
  esac
}

os_check() {
  [[ -r /etc/os-release ]] || die "/etc/os-release not found."
  # shellcheck disable=SC1091
  source /etc/os-release
  case "${ID:-}" in ubuntu|debian) ;; *) die "This beta supports Ubuntu/Debian only. Detected: ${ID:-unknown}" ;; esac
  have systemctl || die "systemd is required."
  have apt-get || die "apt-get is required."
}

project_file() { printf '%s/%s.json' "$PROJECTS_DIR" "$1"; }
profile_file() { printf '%s/%s.json' "$PROFILES_DIR" "$1"; }

validate_project_json() {
  local file="$1"
  jq -e '
    .schema_version == 2 and
    (.slug|type=="string") and
    (.repo_url|type=="string") and
    (.repo_full_name|type=="string") and
    (.runner_user|type=="string") and
    (.base_dir|type=="string") and
    (.labels|type=="array") and
    (.rootless_docker|type=="boolean")
  ' "$file" >/dev/null || die "Invalid project state: $file"
}

save_project() {
  local slug="$1" repo_url="$2" repo_full="$3" runner_user="$4" base_dir="$5" labels_csv="$6" rootless="$7" scan_ref="${8:-}"
  local file tmp
  file="$(project_file "$slug")"; tmp="${file}.tmp"
  jq -n \
    --argjson schema_version "$STATE_SCHEMA_VERSION" \
    --arg slug "$slug" --arg repo_url "$repo_url" --arg repo_full_name "$repo_full" \
    --arg runner_user "$runner_user" --arg base_dir "$base_dir" --arg labels "$labels_csv" \
    --argjson rootless "$rootless" --arg scan_ref "$scan_ref" --arg now "$(utc_now)" \
    '{schema_version:$schema_version,slug:$slug,target_type:"repository",repo_url:$repo_url,repo_full_name:$repo_full_name,runner_user:$runner_user,base_dir:$base_dir,labels:($labels|split(",")|map(select(length>0))|unique),rootless_docker:$rootless,scan_ref:(if $scan_ref=="" then null else $scan_ref end),created_at:$now,updated_at:$now}' \
    >"$tmp"
  chmod 600 "$tmp"; mv "$tmp" "$file"
}

update_project_timestamp() {
  local file="$1" tmp="${file}.tmp"
  jq --arg now "$(utc_now)" '.updated_at=$now' "$file" >"$tmp" && chmod 600 "$tmp" && mv "$tmp" "$file"
}

load_project() {
  local slug="$1" file
  file="$(project_file "$slug")"
  [[ -r "$file" ]] || die "Unknown project '$slug'. Run '$0 list'."
  validate_project_json "$file"
  PROJECT_SLUG="$(jq -r .slug "$file")"
  REPO_URL="$(jq -r .repo_url "$file")"
  REPO_FULL_NAME="$(jq -r .repo_full_name "$file")"
  RUNNER_USER="$(jq -r .runner_user "$file")"
  BASE_DIR="$(jq -r .base_dir "$file")"
  CUSTOM_LABELS="$(jq -r '.labels|join(",")' "$file")"
  ROOTLESS_DOCKER="$(jq -r .rootless_docker "$file")"
  SCAN_REF="$(jq -r '.scan_ref // empty' "$file")"
}

migrate_legacy_state() {
  need_root
  init_dirs
  local conf slug repo_url repo_full runner_user base_dir labels rootless
  shopt -s nullglob
  for conf in "$PROJECTS_DIR"/*.conf; do
    # Legacy files were generated by ghrctl v0.1.0 and are root-only. Parse only known assignments.
    slug="$(sed -nE 's/^PROJECT_SLUG=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    [[ -n "$slug" ]] || continue
    repo_url="$(sed -nE 's/^REPO_URL=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    repo_full="$(sed -nE 's/^REPO_FULL_NAME=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    runner_user="$(sed -nE 's/^RUNNER_USER=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    base_dir="$(sed -nE 's/^BASE_DIR=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    labels="$(sed -nE 's/^CUSTOM_LABELS=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    rootless="$(sed -nE 's/^ROOTLESS_DOCKER=(.*)$/\1/p' "$conf" | xargs printf '%s' 2>/dev/null || true)"
    [[ "$rootless" == "true" || "$rootless" == "false" ]] || rootless=true
    if [[ ! -e "$(project_file "$slug")" ]]; then
      save_project "$slug" "$repo_url" "$repo_full" "$runner_user" "$base_dir" "$labels" "$rootless"
      mv "$conf" "${conf}.migrated"
      success "Migrated legacy state for $slug to JSON."
    fi
  done
  shopt -u nullglob
}

